services:
  shiny-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: shinyapps_3838:local
    ports:
      - '3838:3838'
    volumes:
      - ./logs:/var/log/shiny-server
    restart: always
